import type { Metadata } from "next";
import "../styles/variables.css";
import "../styles/globals.css";
import { Analytics } from "@vercel/analytics/react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={`antialiased`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
